### ISSUE TITLE
`encrypted_key_basic.owl` is not extractable

### ISSUE THREAD

**Issue by cfm** [secure-foundations/owl#18]
I'm looking into OWL after @gancherj's [presentation to the Usable Formal Methods Research Group at IETF 118](https://datatracker.ietf.org/doc/slides-118-ufmrg-verifying-security-protocols-end-to-end-with-owl/).  (For which: thank you! :-)  I'm having trouble getting the example `encrypted_key_basic.owl` to extract to Rust:

```sh-session
user@dev:~/owl$ git reset --hard
HEAD is now at b63159a Sync with dev
user@dev:~/owl$ cabal run owl -- -e docs/encrypted_key_basic.owl
Up to date
Found smtcache file: docs/encrypted_key_basic.owl.smtcache
Typechecking success!
Extraction error: Locality Top_alice does not have a defined main function. For extraction, there should be a defined entry point function that must not take arguments: def Top_alice_main () @ Top_alice
```

Okay, let's try:

```patch
--- a/docs/encrypted_key_basic.owl
+++ b/docs/encrypted_key_basic.owl
@@ -20,7 +20,7 @@ enum Result {
     | NoResult
 }
 
-def alice () @ alice
+def alice_main () @ alice
      : if sec(k_data) then Result else Data<adv> = 
     let c = aenc(get(psk), get(k_data)) in
     output c;
@@ -32,7 +32,7 @@ def alice () @ alice
      | None => NoResult()
     }
     
-def bob () @ bob : Unit =
+def bob_main () @ bob : Unit =
     input i in // i : Data<adv>
     corr_case psk in
     case adec(get(psk), i)  {
```
```sh-session
user@dev:~/owl$ cabal run owl -- -e docs/encrypted_key_basic.owl
Up to date
Found smtcache file: docs/encrypted_key_basic.owl.smtcache
Typechecking success!
Extraction error: Found a call to `output` without a destination specified. For extraction, all outputs must have a destination locality specified.
```

Okay, let's try:

```patch
--- a/docs/encrypted_key_basic.owl
+++ b/docs/encrypted_key_basic.owl
@@ -20,10 +20,10 @@ enum Result {
     | NoResult
 }
 
-def alice () @ alice
+def alice_main () @ alice
      : if sec(k_data) then Result else Data<adv> = 
     let c = aenc(get(psk), get(k_data)) in
-    output c;
+    output c to endpoint(bob);
     input i in 
     corr_case k_data in
     let res = adec(get(k_data), i) in 
@@ -32,13 +32,13 @@ def alice () @ alice
      | None => NoResult()
     }
     
-def bob () @ bob : Unit =
+def bob_main () @ bob : Unit =
     input i in // i : Data<adv>
     corr_case psk in
     case adec(get(psk), i)  {
      | Some k => 
         let c = aenc(k, get(x)) in
-        output c
+        output c to endpoint(alice)
      | None => ()
     }
```
```sh-session
user@dev:~/owl$ cabal run owl -- -e docs/encrypted_key_basic.owl
Up to date
Found smtcache file: docs/encrypted_key_basic.owl.smtcache
Typechecking success!
Extraction error: Undefined symbol:  Top.unit
```

I know from <https://github.com/secure-foundations/owl/issues/9#issuecomment-1661307377> that there may be some drift across branches, so I'd be grateful for any pointers on what's currently expected to be extractable for demonstration purposes.

**Comment by gancherj** [comment]
Hi there! Thank you for checking out Owl! :) 

The issue you found was due to internal renaming of a few constants that were not correctly propagated to extraction.  I have pushed the fix to main [here](https://github.com/secure-foundations/owl/commit/7a6de5d6e1f2736a5e5f9b4a55a72c6085126d3c). With this change, the `encrypted_key_basic` example now extracts. Thank you for pointing out the issue!

**Comment by cfm** [comment]
Thanks for the speedy reply, @gancherj.  7a6de5d6e1f2736a5e5f9b4a55a72c6085126d3c works for me _with_ my patch above, which I've proposed in #19.  Of course, let me know if I'm missing something....  :-)

**Comment by gancherj** [comment]
Additionally -- as you may have noticed, documentation for Owl is currently very light. If you have any questions about how to use Owl, or what guarantees Owl gives, please feel free to reach out.

**Comment by cfm** [comment]
Thank you!  Would you prefer e-mail or individual tickets here (or perhaps GitHub Discussions)?

**Comment by gancherj** [comment]
For the time being, feel free to open up an issue -- we can then close these issues with extra documentation.
