### ISSUE TITLE
Running demo gives parse error

### ISSUE THREAD

**Issue by sanjit-bhat** [secure-foundations/owl#9]
Hello! I tried running the `encrypted_key_basic` demo example, and I got the following error. Do you know how I can resolve this?
```bash
> cabal run owl -- docs/encrypted_key_basic.owl
Up to date
parse error: "encrypted_key_basic.owl" (line 23, column 11):
unexpected "("
expecting "<" or "@"
```
Line 23 is the start of the `alice` definition. [See here](https://github.com/secure-foundations/owl/blob/de46e69a1520572ddc8d0988125f7f77224b6b15/docs/encrypted_key_basic.owl) for a link to the file/commit.
```
def alice () @ alice
```

**Comment by sanjit-bhat** [comment]
Ah, I just found the version of `encrypted_key` that successfully type-checks: [link](https://github.com/secure-foundations/owl/blob/de46e69a1520572ddc8d0988125f7f77224b6b15/tests/success/encrypted_key.owl).

**Comment by gancherj** [comment]
Hi Sanjit! The stuff in `docs/` is unfinished -- indeed, the example was out of date (but fixed now in the most recent commit). We plan to add more docs soon -- please feel free to reach out if you have any questions until then. 

BTW, the main branch is under new developments, so the Owl syntax is subject to change. The release [here](https://github.com/secure-foundations/owl/releases/tag/ieee-sp-2023) corresponds to the S&P submission.

**Comment by sanjit-bhat** [comment]
Got it, thanks!
